// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Job {
    /**
     * Creates a new Job instance.
     * @param {Partial<Job>} [$$source = {}] - The source object to create the Job.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("company" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["company"] = "";
        }
        if (!("location" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["location"] = "";
        }
        if (!("sector" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sector"] = "";
        }
        if (!("salary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["salary"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("skills" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["skills"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("match_score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["match_score"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("applied_date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["applied_date"] = "";
        }
        if (!("interview_date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interview_date"] = "";
        }
        if (!("offer_date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["offer_date"] = "";
        }
        if (!("offer_salary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["offer_salary"] = "";
        }
        if (!("offer_benefits" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["offer_benefits"] = "";
        }
        if (!("offer_equity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["offer_equity"] = "";
        }
        if (!("gap_analysis" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gap_analysis"] = "";
        }
        if (!("scraped_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scraped_at"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Job instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Job}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Job(/** @type {Partial<Job>} */($$parsedSource));
    }
}
