// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as JobService from "./jobservice.js";
export {
    JobService
};

export {
    Config,
    JobAnalysis,
    ScrapeResult
} from "./models.js";
