// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scraper$0 from "./scraper/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} title
 * @param {string} company
 * @param {string} description
 * @returns {$CancellablePromise<$models.JobAnalysis | null>}
 */
export function AnalyzeJob(title, company, description) {
    return $Call.ByID(2625941457, title, company, description).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearAllJobs() {
    return $Call.ByID(4068941418);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteJob(id) {
    return $Call.ByID(1245916576, id);
}

/**
 * @param {string} resumePath
 * @returns {$CancellablePromise<$models.ScrapeResult | null>}
 */
export function ExtractResume(resumePath) {
    return $Call.ByID(2235353992, resumePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * FilterRemoteJobs scans all new/unfiltered jobs and marks them remote/not_remote using keyword matching
 * @returns {$CancellablePromise<$models.ScrapeResult | null>}
 */
export function FilterRemoteJobs() {
    return $Call.ByID(2678965270).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function GetConfig() {
    return $Call.ByID(3882559300).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: number }>}
 */
export function GetCounts() {
    return $Call.ByID(1238644790).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetDefaultQueries() {
    return $Call.ByID(4119305041).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} jobID
 * @returns {$CancellablePromise<string>}
 */
export function GetGapAnalysis(jobID) {
    return $Call.ByID(881577236, jobID);
}

/**
 * @param {string} status
 * @returns {$CancellablePromise<db$0.Job[]>}
 */
export function GetJobs(status) {
    return $Call.ByID(2795355898, status).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<scraper$0.KeywordCount[]>}
 */
export function GetKeywordStats() {
    return $Call.ByID(547884624).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetMarketAnalysis() {
    return $Call.ByID(2311011408);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetPositions() {
    return $Call.ByID(3306176466).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Init() {
    return $Call.ByID(85783268);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function RecommendPositions() {
    return $Call.ByID(2959451308).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string[]} positions
 * @returns {$CancellablePromise<void>}
 */
export function SavePositions(positions) {
    return $Call.ByID(2511417425, positions);
}

/**
 * @param {string} customQuery
 * @returns {$CancellablePromise<$models.ScrapeResult | null>}
 */
export function ScrapeJobs(customQuery) {
    return $Call.ByID(2522943762, customQuery).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetConfig(key, value) {
    return $Call.ByID(979551488, key, value);
}

/**
 * @param {string} id
 * @param {string} notes
 * @returns {$CancellablePromise<void>}
 */
export function UpdateNotes(id, notes) {
    return $Call.ByID(1038548876, id, notes);
}

/**
 * @param {string} id
 * @param {string} salary
 * @param {string} benefits
 * @param {string} equity
 * @returns {$CancellablePromise<void>}
 */
export function UpdateOffer(id, salary, benefits, equity) {
    return $Call.ByID(1137842659, id, salary, benefits, equity);
}

/**
 * @param {string} id
 * @param {string} status
 * @returns {$CancellablePromise<void>}
 */
export function UpdateStatus(id, status) {
    return $Call.ByID(3130938705, id, status);
}

// Private type creation functions
const $$createType0 = $models.JobAnalysis.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ScrapeResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.Config.createFrom;
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = db$0.Job.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = scraper$0.KeywordCount.createFrom;
const $$createType10 = $Create.Array($$createType9);
