// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("serpapi_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serpapi_key"] = "";
        }
        if (!("location" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["location"] = "";
        }
        if (!("queries" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["queries"] = [];
        }
        if (!("resume_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resume_path"] = "";
        }
        if (!("resume_text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resume_text"] = "";
        }
        if (!("keywords" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["keywords"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("queries" in $$parsedSource) {
            $$parsedSource["queries"] = $$createField2_0($$parsedSource["queries"]);
        }
        if ("keywords" in $$parsedSource) {
            $$parsedSource["keywords"] = $$createField5_0($$parsedSource["keywords"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class JobAnalysis {
    /**
     * Creates a new JobAnalysis instance.
     * @param {Partial<JobAnalysis>} [$$source = {}] - The source object to create the JobAnalysis.
     */
    constructor($$source = {}) {
        if (!("salary_range" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["salary_range"] = "";
        }
        if (!("location_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["location_type"] = "";
        }
        if (!("experience" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["experience"] = "";
        }
        if (!("must_have" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["must_have"] = "";
        }
        if (!("nice_to_have" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nice_to_have"] = "";
        }
        if (!("red_flags" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["red_flags"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobAnalysis instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JobAnalysis}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JobAnalysis(/** @type {Partial<JobAnalysis>} */($$parsedSource));
    }
}

export class ScrapeResult {
    /**
     * Creates a new ScrapeResult instance.
     * @param {Partial<ScrapeResult>} [$$source = {}] - The source object to create the ScrapeResult.
     */
    constructor($$source = {}) {
        if (!("jobs_found" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["jobs_found"] = 0;
        }
        if (!("errors" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScrapeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScrapeResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField1_0($$parsedSource["errors"]);
        }
        return new ScrapeResult(/** @type {Partial<ScrapeResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
