// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class KeywordCount {
    /**
     * Creates a new KeywordCount instance.
     * @param {Partial<KeywordCount>} [$$source = {}] - The source object to create the KeywordCount.
     */
    constructor($$source = {}) {
        if (!("keyword" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyword"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeywordCount instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeywordCount}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeywordCount(/** @type {Partial<KeywordCount>} */($$parsedSource));
    }
}
